spring:
  application:
    name: task_management-system
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days
  datasource:
    url: jdbc:mysql://localhost:3306/task_management
    username: root
    password: 135790@Abv
  jpa:

    hibernate:
      ddl-auto: update
    open-in-view: false
